require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe V1::PagesController do

  # This should return the minimal set of attributes required to create a valid
  # V1::Page. As you add validations to V1::Page, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all v1_pages as @v1_pages" do
      page = V1::Page.create! valid_attributes
      get :index
      assigns(:v1_pages).should eq([page])
    end
  end

  describe "GET show" do
    it "assigns the requested v1_page as @v1_page" do
      page = V1::Page.create! valid_attributes
      get :show, :id => page.id.to_s
      assigns(:v1_page).should eq(page)
    end
  end

  describe "GET new" do
    it "assigns a new v1_page as @v1_page" do
      get :new
      assigns(:v1_page).should be_a_new(V1::Page)
    end
  end

  describe "GET edit" do
    it "assigns the requested v1_page as @v1_page" do
      page = V1::Page.create! valid_attributes
      get :edit, :id => page.id.to_s
      assigns(:v1_page).should eq(page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new V1::Page" do
        expect {
          post :create, :v1_page => valid_attributes
        }.to change(V1::Page, :count).by(1)
      end

      it "assigns a newly created v1_page as @v1_page" do
        post :create, :v1_page => valid_attributes
        assigns(:v1_page).should be_a(V1::Page)
        assigns(:v1_page).should be_persisted
      end

      it "redirects to the created v1_page" do
        post :create, :v1_page => valid_attributes
        response.should redirect_to(V1::Page.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved v1_page as @v1_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        V1::Page.any_instance.stub(:save).and_return(false)
        post :create, :v1_page => {}
        assigns(:v1_page).should be_a_new(V1::Page)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        V1::Page.any_instance.stub(:save).and_return(false)
        post :create, :v1_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested v1_page" do
        page = V1::Page.create! valid_attributes
        # Assuming there are no other v1_pages in the database, this
        # specifies that the V1::Page created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        V1::Page.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => page.id, :v1_page => {'these' => 'params'}
      end

      it "assigns the requested v1_page as @v1_page" do
        page = V1::Page.create! valid_attributes
        put :update, :id => page.id, :v1_page => valid_attributes
        assigns(:v1_page).should eq(page)
      end

      it "redirects to the v1_page" do
        page = V1::Page.create! valid_attributes
        put :update, :id => page.id, :v1_page => valid_attributes
        response.should redirect_to(page)
      end
    end

    describe "with invalid params" do
      it "assigns the v1_page as @v1_page" do
        page = V1::Page.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        V1::Page.any_instance.stub(:save).and_return(false)
        put :update, :id => page.id.to_s, :v1_page => {}
        assigns(:v1_page).should eq(page)
      end

      it "re-renders the 'edit' template" do
        page = V1::Page.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        V1::Page.any_instance.stub(:save).and_return(false)
        put :update, :id => page.id.to_s, :v1_page => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested v1_page" do
      page = V1::Page.create! valid_attributes
      expect {
        delete :destroy, :id => page.id.to_s
      }.to change(V1::Page, :count).by(-1)
    end

    it "redirects to the v1_pages list" do
      page = V1::Page.create! valid_attributes
      delete :destroy, :id => page.id.to_s
      response.should redirect_to(v1_pages_url)
    end
  end

end
