ITEM_CREATED : <%="#{username}"%> has created a new <%="#{item}"%> and called it <%="#{item_name}"%>
ITEM_UPDATED : <%="#{username}"%> has updated the  <%="#{item} #{item_name}"%>
ITEM_DELETED : <%="#{username}"%> moved <%="#{item} #{item_name}"%> to trash
CATEGORY_CREATED : <%="#{username}"%> has created a new category and called it <%="#{item}"%>
CATEGORY_DELETED : <%="#{username}"%> moved category <%="#{item}"%> to trash
CATEGORY_UPDATED	: <%="#{username}"%> has updated the category <%="#{item}" %>
BOOKMARK_CREATED : <%="#{username}"%> has created a new bookmark and called it <%="#{item}" %>
BOOKMARK_UPDATED : <%="#{username}"%> has updated the bookmark <%="#{item}" %>
BOOKMARK_DELETED	: <%="#{username}"%> have moved <%="#{item}" %> to trash
PAGE_CREATED : New page has been added to <%="#{item_name}" %>
PAGE_UPDATED	: Page has been updated in <%="#{item_name}" %>
PAGE_DELETED	: <%="#{username}"%> moved <%="#{item_name}" %> to trash
CATEGORY_ADDED_ITEM : <%="#{username}"%> has moved the <%="#{item}" %> into the category <%="#{item_name}" %>
COMMUNITY_CREATED : <%="#{username}"%> has created a new team and called it <%="#{item}"%>
COMMUNITY_UPDATED : <%="#{username}"%> has updated the  <%="#{item} #{item_name}"%>
COMMUNITY_DELETED : <%="#{username}"%> moved team <%="#{item}"%> to trash
SHARE_ATTACHMENT : <%="#{username}"%> has shared the  file <%=" #{item_name}"%> in <%="#{item}"%> team
SHARE_MEET : <%="#{username}"%> has shared the  meet <%=" #{item_name}"%> in <%="#{item}"%> team
USER_ATTACHMENT : <%="#{username}"%> has uploaded a new file and called it <%="#{item}"%>
ATTACHMENT_DOWNLOADED : <%="#{username}"%> has downloaded <%="#{item}"%>
COMMUNITY_INVITED : You have invited <%="#{username}"%> to a virtual team called <%="#{item_name}"%>
COMMUNITY_JOINED : <%="#{username}"%> has joined <%="#{item_name}"%> Virtual Team 
FOLDER_CREATED : <%="#{username}"%> has created a new <%="#{item}"%> and called it <%="#{item_name}"%>
FOLDER_UPDATED : <%="#{username}"%> has updated the  <%="#{item} #{item_name}"%>
FOLDER_DELETED : <%="#{username}"%> moved <%="#{item} #{item_name}"%> to trash
