require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomPagesController do

  # This should return the minimal set of attributes required to create a valid
  # CustomPage. As you add validations to CustomPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all custom_pages as @custom_pages" do
      custom_page = CustomPage.create! valid_attributes
      get :index
      assigns(:custom_pages).should eq([custom_page])
    end
  end

  describe "GET show" do
    it "assigns the requested custom_page as @custom_page" do
      custom_page = CustomPage.create! valid_attributes
      get :show, :id => custom_page.id.to_s
      assigns(:custom_page).should eq(custom_page)
    end
  end

  describe "GET new" do
    it "assigns a new custom_page as @custom_page" do
      get :new
      assigns(:custom_page).should be_a_new(CustomPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested custom_page as @custom_page" do
      custom_page = CustomPage.create! valid_attributes
      get :edit, :id => custom_page.id.to_s
      assigns(:custom_page).should eq(custom_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomPage" do
        expect {
          post :create, :custom_page => valid_attributes
        }.to change(CustomPage, :count).by(1)
      end

      it "assigns a newly created custom_page as @custom_page" do
        post :create, :custom_page => valid_attributes
        assigns(:custom_page).should be_a(CustomPage)
        assigns(:custom_page).should be_persisted
      end

      it "redirects to the created custom_page" do
        post :create, :custom_page => valid_attributes
        response.should redirect_to(CustomPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved custom_page as @custom_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomPage.any_instance.stub(:save).and_return(false)
        post :create, :custom_page => {}
        assigns(:custom_page).should be_a_new(CustomPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomPage.any_instance.stub(:save).and_return(false)
        post :create, :custom_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested custom_page" do
        custom_page = CustomPage.create! valid_attributes
        # Assuming there are no other custom_pages in the database, this
        # specifies that the CustomPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomPage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => custom_page.id, :custom_page => {'these' => 'params'}
      end

      it "assigns the requested custom_page as @custom_page" do
        custom_page = CustomPage.create! valid_attributes
        put :update, :id => custom_page.id, :custom_page => valid_attributes
        assigns(:custom_page).should eq(custom_page)
      end

      it "redirects to the custom_page" do
        custom_page = CustomPage.create! valid_attributes
        put :update, :id => custom_page.id, :custom_page => valid_attributes
        response.should redirect_to(custom_page)
      end
    end

    describe "with invalid params" do
      it "assigns the custom_page as @custom_page" do
        custom_page = CustomPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomPage.any_instance.stub(:save).and_return(false)
        put :update, :id => custom_page.id.to_s, :custom_page => {}
        assigns(:custom_page).should eq(custom_page)
      end

      it "re-renders the 'edit' template" do
        custom_page = CustomPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomPage.any_instance.stub(:save).and_return(false)
        put :update, :id => custom_page.id.to_s, :custom_page => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested custom_page" do
      custom_page = CustomPage.create! valid_attributes
      expect {
        delete :destroy, :id => custom_page.id.to_s
      }.to change(CustomPage, :count).by(-1)
    end

    it "redirects to the custom_pages list" do
      custom_page = CustomPage.create! valid_attributes
      delete :destroy, :id => custom_page.id.to_s
      response.should redirect_to(custom_pages_url)
    end
  end

end
